# Generated by Django 3.1.3 on 2020-11-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201123_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='creacion_fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publicacione',
            name='creacion_fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
