# Generated by Django 3.1.3 on 2020-11-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201123_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacione',
            name='reaccion',
            field=models.IntegerField(default=0),
        ),
    ]
